# Generated by Django 6.0.1 on 2026-01-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0008_datospersonales_mostrar_academicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_academicos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Académico'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Cursos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='Mostrar Experiencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Mostrar Garaje'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_logros',
            field=models.BooleanField(default=True, verbose_name='Mostrar Logros'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_proyectos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Proyectos'),
        ),
    ]
