# Generated by Django 6.0.1 on 2026-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0010_alter_datospersonales_mostrar_academicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoslaborales',
            name='imagen_proyecto',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen del Proyecto'),
        ),
    ]
