# Generated by Django 6.0.1 on 2026-01-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0012_rename_imagen_proyecto_productoslaborales_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoslaborales',
            old_name='imagen',
            new_name='imagen_proyecto',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_academicos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Académico'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Cursos'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Experiencia'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Garaje'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_logros',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Logros'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_proyectos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sección Proyectos'),
        ),
    ]
