# Generated by Django 6.0.1 on 2026-01-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0013_rename_imagen_productoslaborales_imagen_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoslaborales',
            old_name='imagen_proyecto',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_academicos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_cursos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_experiencia',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_garage',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_logros',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_proyectos',
        ),
    ]
