# Generated by Django 6.0.1 on 2026-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0017_datospersonales_mostrar_academicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='archivocv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Archivo CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumen Profesional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_academicos',
            field=models.BooleanField(default=True, verbose_name='Incluir Académico'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='Incluir Cursos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='Incluir Experiencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Incluir Garaje'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_logros',
            field=models.BooleanField(default=True, verbose_name='Incluir Logros'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_proyectos',
            field=models.BooleanField(default=True, verbose_name='Incluir Proyectos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=200),
        ),
    ]
