# Generated by Django 6.0.1 on 2026-01-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0019_alter_datospersonales_mostrar_academicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_academicos',
            field=models.BooleanField(default=True, verbose_name='Incluir Académico'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='Incluir Cursos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='Incluir Experiencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Incluir Garaje'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_logros',
            field=models.BooleanField(default=True, verbose_name='Incluir Logros'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_proyectos',
            field=models.BooleanField(default=True, verbose_name='Incluir Proyectos'),
        ),
    ]
