# Generated by Django 5.0.1 on 2026-01-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0020_alter_datospersonales_mostrar_academicos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='emailempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='idexperiencilaboral',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='lugarempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='idproductoslaborales',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='archivo_recurso',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='documento_interes',
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/previews/', verbose_name='Vista Previa (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='idexperiencia',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='academicos/'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='reconocimientos/previews/', verbose_name='Vista Previa (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='descripcionproducto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='garage/'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='archivo_extra',
            field=models.FileField(blank=True, null=True, upload_to='cursos/extra/'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecurso',
            field=models.CharField(blank=True, db_column='nombrerecurso', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='cursos/', verbose_name='Certificado (PDF)'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='archivocv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_academicos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_logros',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_proyectos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='nombreproducto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/', verbose_name='Certificado (PDF)'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil.datospersonales'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='cursosrealizados',
            table='cursos_realizados',
        ),
        migrations.AlterModelTable(
            name='datospersonales',
            table='datos_personales',
        ),
        migrations.AlterModelTable(
            name='experiencialaboral',
            table='experiencia_laboral',
        ),
        migrations.AlterModelTable(
            name='productosacademicos',
            table='productos_academicos',
        ),
        migrations.AlterModelTable(
            name='productoslaborales',
            table='productos_laborales',
        ),
        migrations.AlterModelTable(
            name='reconocimientos',
            table='reconocimientos',
        ),
        migrations.AlterModelTable(
            name='ventagarage',
            table='venta_garage',
        ),
    ]
