# Generated by Django 5.0.1 on 2026-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0021_alter_cursosrealizados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Curso'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Perfil'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencia',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Experiencia'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Académico'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Proyecto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Reconocimiento'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Garaje'),
        ),
    ]
