# Generated by Django 5.0.1 on 2026-02-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0022_alter_cursosrealizados_idcursorealizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='fechafin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
