# Generated by Django 5.0.1 on 2026-02-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0023_productosacademicos_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'managed': True, 'verbose_name': 'Curso Realizado', 'verbose_name_plural': 'Cursos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'managed': True, 'verbose_name': 'Dato Personal', 'verbose_name_plural': 'Datos Personales'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'managed': True, 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'managed': True, 'verbose_name': 'Producto Académico', 'verbose_name_plural': 'Productos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'managed': True, 'verbose_name': 'Proyecto Laboral', 'verbose_name_plural': 'Proyectos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'managed': True, 'verbose_name': 'Reconocimiento', 'verbose_name_plural': 'Reconocimientos'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'managed': True, 'verbose_name': 'Venta de Garaje', 'verbose_name_plural': 'Venta de Garaje'},
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Curso'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Perfil'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencia',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Experiencia'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Académico'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Proyecto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Reconocimiento'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Garaje'),
        ),
    ]
