# Generated by Django 5.0.1 on 2026-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0024_alter_cursosrealizados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='experiencia/previews/', verbose_name='Vista Previa (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='experiencia/', verbose_name='Certificado Laboral (PDF)'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='academicos/previews/', verbose_name='Vista Previa (PNG/JPG)'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='academicos/', verbose_name='Documento (PDF)'),
        ),
    ]
