# Generated by Django 5.0.1 on 2026-02-02 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0025_experiencialaboral_imagen_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Curso'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencia',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Experiencia'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Académico'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Proyecto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Reconocimiento'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID Garaje'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
