# Generated by Django 5.0.1 on 2026-02-03 01:05

import Perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0027_alter_cursosrealizados_idcursorealizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[Perfil.models.validar_no_futuro], verbose_name='Fecha de Nacimiento'),
        ),
    ]
