# Generated by Django 5.0.1 on 2026-02-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0028_alter_datospersonales_fechanacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'managed': True, 'ordering': ['-fechafin'], 'verbose_name': 'Curso Realizado', 'verbose_name_plural': 'Cursos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'managed': True, 'ordering': ['-fechainiciogestion'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'managed': True, 'ordering': ['-fechafin'], 'verbose_name': 'Producto Académico', 'verbose_name_plural': 'Productos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'managed': True, 'ordering': ['-fechaproducto'], 'verbose_name': 'Proyecto Laboral', 'verbose_name_plural': 'Proyectos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'managed': True, 'ordering': ['-fechareconocimiento'], 'verbose_name': 'Reconocimiento', 'verbose_name_plural': 'Reconocimientos'},
        ),
    ]
